### PR TITLE
First pass at cleaning up documentation

### PR DESCRIPTION
**Pull request by ViridianForge**
- Cleans up README.md
- Pulls Changelog into CHANGELOG.md
  - Used the [KeepAChangelog](https://keepachangelog.com/en/1.0.0/) format
  - Fleshed out the changes with links to greatest degree possible 
- Pulls the core reflection example into an example directory
- Adds an example HelloWorld Server for running examples again
  - Ultimate goal here is use this work to run test cases against once those can be restored

### CODE REVIEW

**Review by wesky93 — DISMISSED** [review]
LGTM!!!!

**Comment by wesky93** [comment]
How about adding a collaborator to Readme?

**Comment by ViridianForge** [comment]
Maintainers / Collaborators section added! Will merge shortly.

**Comment by ViridianForge** [comment]
- Cleans up README.md
-  Pulls Changelog into CHANGELOG.md
-       Used the [KeepAChangelog](https://keepachangelog.com/en/1.0.0/) format
-       Fleshed out the changes with links to greatest degree possible
-  Pulls the core reflection example into an example directory
-  Adds an example HelloWorld Server for running examples again
-      Ultimate goal here is use this work to run test cases against once those can be restored

**Pull request merged**
